appmodel:
  name: app-migration-frontend
  env: dev
  image: quay.io/rtaneja/app-migration-image-build@sha256:1a13a9422701c5147ca25204fea86ff23464ed0dc8568399f2f8e6ea922a1b3a
  resources:
    limits:
      cpu: 0.3
      memory: 500Mi
    requests:
      cpu: 0.3
      memory: 500Mi
# how to build image for local changes
# large amounts of images will be in the nexus server
# How to integrate argo in this?